### ISSUE TITLE
ee key too small

### ISSUE THREAD

**Issue by ananwanan** [cracker0dks/nodeJsVoip#6]
Ubuntu 18.06

nodejs version: 10.19.0

```shell

root@imorning:nodeJsVoip# node server.js 
_tls_common.js:135
      c.context.setCert(cert);
                ^

Error: error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small
    at Object.createSecureContext (_tls_common.js:135:17)
    at Server (_tls_wrap.js:873:27)
    at new Server (https.js:62:14)
    at Object.createServer (https.js:85:10)
    at Object.<anonymous> (/opt/nodeJsVoip/server.js:19:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

```

**Comment by cracker0dks** [comment]
This has to be the old nodejs version. Are you able to update to at least v12 or better v16?

**Comment by ananwanan** [comment]
Regenerate SSL solved the problem.
